version: "3.5"
services:
    server:
        build:
            context: ./server
            dockerfile: ../docker/server.Dockerfile
        networks:
            - backend

    nginx_client:
        restart: always
        build:
            context: ./client
            dockerfile: ../docker/client.Dockerfile
        ports:
            - "80:80"
        depends_on:
            - server
        networks:
            - backend

    db:
        # container 이름은 nginx 설정(.conf)에서 사용할수도 있지만
        # mysql은 사용하지 않는 상태이고, 겹치는 이름이 있으면 실행이 안되므로
        # 지정해주지 않기로함
        build:
            context: ./mysql
            dockerfile: ../docker/mysql.Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_secret
            MYSQL_USER: drstrange
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_secret
            MYSQL_DATABASE: BooleanAvengers
        secrets:
            - mysql_secret
        ports:
            - "3306:3306"
        networks:
            - backend

networks:
    backend:
        driver: bridge

secrets:
    mysql_secret:
        file: secret
